# Generated by Django 5.2.3 on 2026-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company')], default='user', max_length=20),
        ),
    ]
